### ISSUE TITLE
Better link to Ed-DaSH

### ISSUE THREAD

**Issue by ewallace** [edcarp/edcarp.github.io#18]
I hurriedly added a front page link to Ed-DaSH from the edcarp website, in commit 64705d14cef726d0ad7fe694a67ddf70cee29461

We can probably do better?

**Comment by ewallace** [comment]
So nice that this works! Thanks Giacomo for merging.

**Comment by gperu** [comment]
Indeed, thank you and to @marioa arranging this. Sublime, when there are more hands collaborating!
